services:
  postgres:
    container_name: taki-db
    image: postgres:16.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: taki
      POSTGRES_PASSWORD: postgres
    networks:
      - default
  app:
    container_name: taki-app
    image: nmuianga/taki-service:v1.0.0
    # build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://postgres:5432/taki
      DB_SCHEMA: taki
    networks:
      - default
  frontend:
    image: cossaobede/taki-frontend:1.0
    ports:
      - "5173:80"
    depends_on:
      - postgres
      - app
networks:
  default:
    name: taki-network